# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: python

before_install:
  - sudo apt update > /dev/null 2>&1
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;  > /dev/null 2>&1
  - bash miniconda.sh -b -p $HOME/miniconda  > /dev/null 2>&1
  - source "$HOME/miniconda/etc/profile.d/conda.sh"  > /dev/null 2>&1
  - hash -r  > /dev/null 2>&1
  - conda config --set always_yes yes --set changeps1 no  > /dev/null 2>&1
  - conda update -q conda  > /dev/null 2>&1
  - conda update --all && conda install --channel "conda-forge" --channel "anaconda" --channel "r" tensorflow-mkl keras jupyter jupytext numpy pandas r r-devtools r-rgl r-rjava r-mnormt r-purrrogress r-xml libxml2 pandoc r-rjava opencv pkgconfig gfortran_linux-64 && echo "options(repos=structure(c(CRAN='http://cran.r-project.org')))" >> ~/.Rprofile  > /dev/null 2>&1
  - conda info -a  > /dev/null 2>&1
  - conda activate base  > /dev/null 2>&1
  - Rscript -e 'update.packages(ask = F); install.packages(c("devtools","remotes")); remotes::install_cran("pkgdown");'  > /dev/null 2>&1
  - Rscript -e 'devtools::source_url("https://raw.githubusercontent.com/kstawiski/miRNAselector/master/vignettes/setup.R")'  > /dev/null 2>&1

before_script:
  - Rscript -e 'testextra::extract_tests()'
  - Rscript -e 'roxygen2::roxygenise(".", "rd")'

after_success:
  - Rscript -e 'covr::codecov()'

install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *tar.gz

deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
