on:
  push:
    branches: 
      - master

name: R package and environment

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 'latest'
          activate-environment: base

      - name: Setup R
        run: |
          conda update --all && conda install --channel "conda-forge" --channel "anaconda" --channel "r" tensorflow keras jupyter jupytext numpy pandas r r-devtools r-essentials r-biocmanager r-remotes r-keras r-rjava pandoc r-reticulate r-magick r-xml r-rgl opencv pkgconfig && echo "options(repos=structure(c(CRAN='http://cran.r-project.org')))" >> ~/.Rprofile
          Rscript -e "devtools::source_url('https://raw.githubusercontent.com/kstawiski/miRNAselector/master/vignettes/setup.R')"
          Rscript -e "devtools::source_url('https://raw.githubusercontent.com/kstawiski/miRNAselector/master/docker/keras.R')"
          Rscript -e "install.packages(c('pkgdown'))"

      - name: Deploy kstawiski.github.io/miRNAselector
        run: pkgdown::deploy_to_branch()
        shell: Rscript {0}